version: "3.5"

services:
  api01: &api
    build: .

    hostname: api01
    environment:
      - DB_HOSTNAME=db


    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:

    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8082:8080"


  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"


  db:
    image: postgres:16.1
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:

          cpus: "0.13"
          memory: "140MB"


networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1