spring:
  jpa:
    generate-ddl: true
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
  datasource:
    url: jdbc:postgresql://localhost:5432/rinha
    username: admin
    password: 123
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "Brazil/East"
  sql:
    init:
      data-locations: classpath:data.sql